# coding: utf-8

"""
    App::Netdisco

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.050003
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_netdisco
from openapi_netdisco.api.general_api import GeneralApi  # noqa: E501
from openapi_netdisco.rest import ApiException


class TestGeneralApi(unittest.TestCase):
    """GeneralApi unit test stubs"""

    def setUp(self):
        self.api = openapi_netdisco.api.general_api.GeneralApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_login_post(self):
        """Test case for login_post

        """
        pass

    def test_logout_get(self):
        """Test case for logout_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
