# coding: utf-8

"""
    App::Netdisco

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.050003
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_netdisco
from openapi_netdisco.api.search_api import SearchApi  # noqa: E501
from openapi_netdisco.rest import ApiException


class TestSearchApi(unittest.TestCase):
    """SearchApi unit test stubs"""

    def setUp(self):
        self.api = openapi_netdisco.api.search_api.SearchApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_search_device_get(self):
        """Test case for api_v1_search_device_get

        """
        pass

    def test_api_v1_search_node_get(self):
        """Test case for api_v1_search_node_get

        """
        pass

    def test_api_v1_search_port_get(self):
        """Test case for api_v1_search_port_get

        """
        pass

    def test_api_v1_search_vlan_get(self):
        """Test case for api_v1_search_vlan_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
