# coding: utf-8

"""
    App::Netdisco

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.050003
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_netdisco
from openapi_netdisco.models.vlan import Vlan  # noqa: E501
from openapi_netdisco.rest import ApiException

class TestVlan(unittest.TestCase):
    """Vlan unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Vlan
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_netdisco.models.vlan.Vlan()  # noqa: E501
        if include_optional :
            return Vlan(
                ip = '', 
                vlan = '', 
                description = '', 
                creation = '', 
                last_discover = ''
            )
        else :
            return Vlan(
                ip = '',
                vlan = '',
        )

    def testVlan(self):
        """Test Vlan"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
