# coding: utf-8

"""
    App::Netdisco

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.050003
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_netdisco
from openapi_netdisco.api.objects_api import ObjectsApi  # noqa: E501
from openapi_netdisco.rest import ApiException


class TestObjectsApi(unittest.TestCase):
    """ObjectsApi unit test stubs"""

    def setUp(self):
        self.api = openapi_netdisco.api.objects_api.ObjectsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_object_device_ip_device_ips_get(self):
        """Test case for api_v1_object_device_ip_device_ips_get

        """
        pass

    def test_api_v1_object_device_ip_get(self):
        """Test case for api_v1_object_device_ip_get

        """
        pass

    def test_api_v1_object_device_ip_modules_get(self):
        """Test case for api_v1_object_device_ip_modules_get

        """
        pass

    def test_api_v1_object_device_ip_nodes_get(self):
        """Test case for api_v1_object_device_ip_nodes_get

        """
        pass

    def test_api_v1_object_device_ip_port_port_active_nodes_get(self):
        """Test case for api_v1_object_device_ip_port_port_active_nodes_get

        """
        pass

    def test_api_v1_object_device_ip_port_port_active_nodes_with_age_get(self):
        """Test case for api_v1_object_device_ip_port_port_active_nodes_with_age_get

        """
        pass

    def test_api_v1_object_device_ip_port_port_agg_master_get(self):
        """Test case for api_v1_object_device_ip_port_port_agg_master_get

        """
        pass

    def test_api_v1_object_device_ip_port_port_get(self):
        """Test case for api_v1_object_device_ip_port_port_get

        """
        pass

    def test_api_v1_object_device_ip_port_port_last_node_get(self):
        """Test case for api_v1_object_device_ip_port_port_last_node_get

        """
        pass

    def test_api_v1_object_device_ip_port_port_logs_get(self):
        """Test case for api_v1_object_device_ip_port_port_logs_get

        """
        pass

    def test_api_v1_object_device_ip_port_port_neighbor_get(self):
        """Test case for api_v1_object_device_ip_port_port_neighbor_get

        """
        pass

    def test_api_v1_object_device_ip_port_port_nodes_get(self):
        """Test case for api_v1_object_device_ip_port_port_nodes_get

        """
        pass

    def test_api_v1_object_device_ip_port_port_nodes_with_age_get(self):
        """Test case for api_v1_object_device_ip_port_port_nodes_with_age_get

        """
        pass

    def test_api_v1_object_device_ip_port_port_power_get(self):
        """Test case for api_v1_object_device_ip_port_port_power_get

        """
        pass

    def test_api_v1_object_device_ip_port_port_properties_get(self):
        """Test case for api_v1_object_device_ip_port_port_properties_get

        """
        pass

    def test_api_v1_object_device_ip_port_port_ssid_get(self):
        """Test case for api_v1_object_device_ip_port_port_ssid_get

        """
        pass

    def test_api_v1_object_device_ip_port_port_vlans_get(self):
        """Test case for api_v1_object_device_ip_port_port_vlans_get

        """
        pass

    def test_api_v1_object_device_ip_port_port_wireless_get(self):
        """Test case for api_v1_object_device_ip_port_port_wireless_get

        """
        pass

    def test_api_v1_object_device_ip_port_vlans_get(self):
        """Test case for api_v1_object_device_ip_port_vlans_get

        """
        pass

    def test_api_v1_object_device_ip_ports_get(self):
        """Test case for api_v1_object_device_ip_ports_get

        """
        pass

    def test_api_v1_object_device_ip_powered_ports_get(self):
        """Test case for api_v1_object_device_ip_powered_ports_get

        """
        pass

    def test_api_v1_object_device_ip_ssids_get(self):
        """Test case for api_v1_object_device_ip_ssids_get

        """
        pass

    def test_api_v1_object_device_ip_vlans_get(self):
        """Test case for api_v1_object_device_ip_vlans_get

        """
        pass

    def test_api_v1_object_device_ip_wireless_ports_get(self):
        """Test case for api_v1_object_device_ip_wireless_ports_get

        """
        pass

    def test_api_v1_object_vlan_vlan_nodes_get(self):
        """Test case for api_v1_object_vlan_vlan_nodes_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
