# coding: utf-8

"""
    App::Netdisco

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.050003
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from openapi_netdisco.configuration import Configuration


class Address(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'ip': 'str',
        'alias': 'str',
        'subnet': 'str',
        'port': 'str',
        'dns': 'str',
        'creation': 'str'
    }

    attribute_map = {
        'ip': 'ip',
        'alias': 'alias',
        'subnet': 'subnet',
        'port': 'port',
        'dns': 'dns',
        'creation': 'creation'
    }

    def __init__(self, ip=None, alias=None, subnet=None, port=None, dns=None, creation=None, local_vars_configuration=None):  # noqa: E501
        """Address - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._ip = None
        self._alias = None
        self._subnet = None
        self._port = None
        self._dns = None
        self._creation = None
        self.discriminator = None

        if ip is not None:
            self.ip = ip
        self.alias = alias
        if subnet is not None:
            self.subnet = subnet
        if port is not None:
            self.port = port
        if dns is not None:
            self.dns = dns
        if creation is not None:
            self.creation = creation

    @property
    def ip(self):
        """Gets the ip of this Address.  # noqa: E501


        :return: The ip of this Address.  # noqa: E501
        :rtype: str
        """
        return self._ip

    @ip.setter
    def ip(self, ip):
        """Sets the ip of this Address.


        :param ip: The ip of this Address.  # noqa: E501
        :type ip: str
        """

        self._ip = ip

    @property
    def alias(self):
        """Gets the alias of this Address.  # noqa: E501


        :return: The alias of this Address.  # noqa: E501
        :rtype: str
        """
        return self._alias

    @alias.setter
    def alias(self, alias):
        """Sets the alias of this Address.


        :param alias: The alias of this Address.  # noqa: E501
        :type alias: str
        """
        if self.local_vars_configuration.client_side_validation and alias is None:  # noqa: E501
            raise ValueError("Invalid value for `alias`, must not be `None`")  # noqa: E501

        self._alias = alias

    @property
    def subnet(self):
        """Gets the subnet of this Address.  # noqa: E501


        :return: The subnet of this Address.  # noqa: E501
        :rtype: str
        """
        return self._subnet

    @subnet.setter
    def subnet(self, subnet):
        """Sets the subnet of this Address.


        :param subnet: The subnet of this Address.  # noqa: E501
        :type subnet: str
        """

        self._subnet = subnet

    @property
    def port(self):
        """Gets the port of this Address.  # noqa: E501


        :return: The port of this Address.  # noqa: E501
        :rtype: str
        """
        return self._port

    @port.setter
    def port(self, port):
        """Sets the port of this Address.


        :param port: The port of this Address.  # noqa: E501
        :type port: str
        """

        self._port = port

    @property
    def dns(self):
        """Gets the dns of this Address.  # noqa: E501


        :return: The dns of this Address.  # noqa: E501
        :rtype: str
        """
        return self._dns

    @dns.setter
    def dns(self, dns):
        """Sets the dns of this Address.


        :param dns: The dns of this Address.  # noqa: E501
        :type dns: str
        """

        self._dns = dns

    @property
    def creation(self):
        """Gets the creation of this Address.  # noqa: E501


        :return: The creation of this Address.  # noqa: E501
        :rtype: str
        """
        return self._creation

    @creation.setter
    def creation(self, creation):
        """Sets the creation of this Address.


        :param creation: The creation of this Address.  # noqa: E501
        :type creation: str
        """

        self._creation = creation

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Address):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Address):
            return True

        return self.to_dict() != other.to_dict()
